/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/_admin'
import { Route as BoutiqueRouteImport } from './routes/boutique'
import { Route as PanierRouteImport } from './routes/panier'
import { Route as AdminIndexRouteImport } from './routes/_admin/index'
import { Route as AdminAnalyticsRouteImport } from './routes/_admin/analytics'
import { Route as AdminAssistanceRouteImport } from './routes/_admin/assistance'
import { Route as AdminCatalogueRouteImport } from './routes/_admin/catalogue'
import { Route as AdminClientsRouteImport } from './routes/_admin/clients'
import { Route as AdminCommandesRouteImport } from './routes/_admin/commandes'
import { Route as AdminFournisseursRouteImport } from './routes/_admin/fournisseurs'
import { Route as AdminIaRouteImport } from './routes/_admin/ia'
import { Route as AdminIntegrationsRouteImport } from './routes/_admin/integrations'
import { Route as AdminParametresRouteImport } from './routes/_admin/parametres'
import { Route as AdminPaymentRouteImport } from './routes/_admin/payment'
import { Route as AdminProduitsRouteImport } from './routes/_admin/produits'
import { Route as AdminProduitsGagnantsRouteImport } from './routes/_admin/produits-gagnants'
import { Route as AdminReglesPrixRouteImport } from './routes/_admin/regles-prix'
import { Route as BoutiqueIdRouteImport } from './routes/boutique.$id'
import { Route as PaiementOrderIdRouteImport } from './routes/paiement.$orderId'

const AdminRoute = AdminRouteImport.update({
  id: '/_admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BoutiqueRoute = BoutiqueRouteImport.update({
  id: '/boutique',
  path: '/boutique',
  getParentRoute: () => rootRouteImport,
} as any)
const PanierRoute = PanierRouteImport.update({
  id: '/panier',
  path: '/panier',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any)
const AdminAssistanceRoute = AdminAssistanceRouteImport.update({
  id: '/assistance',
  path: '/assistance',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCatalogueRoute = AdminCatalogueRouteImport.update({
  id: '/catalogue',
  path: '/catalogue',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClientsRoute = AdminClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCommandesRoute = AdminCommandesRouteImport.update({
  id: '/commandes',
  path: '/commandes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFournisseursRoute = AdminFournisseursRouteImport.update({
  id: '/fournisseurs',
  path: '/fournisseurs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIaRoute = AdminIaRouteImport.update({
  id: '/ia',
  path: '/ia',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntegrationsRoute = AdminIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => AdminRoute,
} as any)
const AdminParametresRoute = AdminParametresRouteImport.update({
  id: '/parametres',
  path: '/parametres',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPaymentRoute = AdminPaymentRouteImport.update({
  id: '/payment',
  path: '/payment',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsRoute = AdminProduitsRouteImport.update({
  id: '/produits',
  path: '/produits',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProduitsGagnantsRoute = AdminProduitsGagnantsRouteImport.update({
  id: '/produits-gagnants',
  path: '/produits-gagnants',
  getParentRoute: () => AdminRoute,
} as any)
const AdminReglesPrixRoute = AdminReglesPrixRouteImport.update({
  id: '/regles-prix',
  path: '/regles-prix',
  getParentRoute: () => AdminRoute,
} as any)
const BoutiqueIdRoute = BoutiqueIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => BoutiqueRoute,
} as any)
const PaiementOrderIdRoute = PaiementOrderIdRouteImport.update({
  id: '/paiement/$orderId',
  path: '/paiement/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AdminIndexRoute
  '/boutique': typeof BoutiqueRouteWithChildren
  '/panier': typeof PanierRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/assistance': typeof AdminAssistanceRoute
  '/catalogue': typeof AdminCatalogueRoute
  '/clients': typeof AdminClientsRoute
  '/commandes': typeof AdminCommandesRoute
  '/fournisseurs': typeof AdminFournisseursRoute
  '/ia': typeof AdminIaRoute
  '/integrations': typeof AdminIntegrationsRoute
  '/parametres': typeof AdminParametresRoute
  '/payment': typeof AdminPaymentRoute
  '/produits': typeof AdminProduitsRoute
  '/produits-gagnants': typeof AdminProduitsGagnantsRoute
  '/regles-prix': typeof AdminReglesPrixRoute
  '/boutique/$id': typeof BoutiqueIdRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
}
export interface FileRoutesByTo {
  '/boutique': typeof BoutiqueRouteWithChildren
  '/panier': typeof PanierRoute
  '/analytics': typeof AdminAnalyticsRoute
  '/assistance': typeof AdminAssistanceRoute
  '/catalogue': typeof AdminCatalogueRoute
  '/clients': typeof AdminClientsRoute
  '/commandes': typeof AdminCommandesRoute
  '/fournisseurs': typeof AdminFournisseursRoute
  '/ia': typeof AdminIaRoute
  '/integrations': typeof AdminIntegrationsRoute
  '/parametres': typeof AdminParametresRoute
  '/payment': typeof AdminPaymentRoute
  '/produits': typeof AdminProduitsRoute
  '/produits-gagnants': typeof AdminProduitsGagnantsRoute
  '/regles-prix': typeof AdminReglesPrixRoute
  '/boutique/$id': typeof BoutiqueIdRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
  '/': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_admin': typeof AdminRouteWithChildren
  '/boutique': typeof BoutiqueRouteWithChildren
  '/panier': typeof PanierRoute
  '/_admin/analytics': typeof AdminAnalyticsRoute
  '/_admin/assistance': typeof AdminAssistanceRoute
  '/_admin/catalogue': typeof AdminCatalogueRoute
  '/_admin/clients': typeof AdminClientsRoute
  '/_admin/commandes': typeof AdminCommandesRoute
  '/_admin/fournisseurs': typeof AdminFournisseursRoute
  '/_admin/ia': typeof AdminIaRoute
  '/_admin/integrations': typeof AdminIntegrationsRoute
  '/_admin/parametres': typeof AdminParametresRoute
  '/_admin/payment': typeof AdminPaymentRoute
  '/_admin/produits': typeof AdminProduitsRoute
  '/_admin/produits-gagnants': typeof AdminProduitsGagnantsRoute
  '/_admin/regles-prix': typeof AdminReglesPrixRoute
  '/boutique/$id': typeof BoutiqueIdRoute
  '/paiement/$orderId': typeof PaiementOrderIdRoute
  '/_admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/boutique'
    | '/panier'
    | '/analytics'
    | '/assistance'
    | '/catalogue'
    | '/clients'
    | '/commandes'
    | '/fournisseurs'
    | '/ia'
    | '/integrations'
    | '/parametres'
    | '/payment'
    | '/produits'
    | '/produits-gagnants'
    | '/regles-prix'
    | '/boutique/$id'
    | '/paiement/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/boutique'
    | '/panier'
    | '/analytics'
    | '/assistance'
    | '/catalogue'
    | '/clients'
    | '/commandes'
    | '/fournisseurs'
    | '/ia'
    | '/integrations'
    | '/parametres'
    | '/payment'
    | '/produits'
    | '/produits-gagnants'
    | '/regles-prix'
    | '/boutique/$id'
    | '/paiement/$orderId'
    | '/'
  id:
    | '__root__'
    | '/_admin'
    | '/boutique'
    | '/panier'
    | '/_admin/analytics'
    | '/_admin/assistance'
    | '/_admin/catalogue'
    | '/_admin/clients'
    | '/_admin/commandes'
    | '/_admin/fournisseurs'
    | '/_admin/ia'
    | '/_admin/integrations'
    | '/_admin/parametres'
    | '/_admin/payment'
    | '/_admin/produits'
    | '/_admin/produits-gagnants'
    | '/_admin/regles-prix'
    | '/boutique/$id'
    | '/paiement/$orderId'
    | '/_admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AdminRoute: typeof AdminRouteWithChildren
  BoutiqueRoute: typeof BoutiqueRouteWithChildren
  PanierRoute: typeof PanierRoute
  PaiementOrderIdRoute: typeof PaiementOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_admin': {
      id: '/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/boutique': {
      id: '/boutique'
      path: '/boutique'
      fullPath: '/boutique'
      preLoaderRoute: typeof BoutiqueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/panier': {
      id: '/panier'
      path: '/panier'
      fullPath: '/panier'
      preLoaderRoute: typeof PanierRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_admin/': {
      id: '/_admin/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/analytics': {
      id: '/_admin/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/assistance': {
      id: '/_admin/assistance'
      path: '/assistance'
      fullPath: '/assistance'
      preLoaderRoute: typeof AdminAssistanceRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/catalogue': {
      id: '/_admin/catalogue'
      path: '/catalogue'
      fullPath: '/catalogue'
      preLoaderRoute: typeof AdminCatalogueRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/clients': {
      id: '/_admin/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AdminClientsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/commandes': {
      id: '/_admin/commandes'
      path: '/commandes'
      fullPath: '/commandes'
      preLoaderRoute: typeof AdminCommandesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/fournisseurs': {
      id: '/_admin/fournisseurs'
      path: '/fournisseurs'
      fullPath: '/fournisseurs'
      preLoaderRoute: typeof AdminFournisseursRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/ia': {
      id: '/_admin/ia'
      path: '/ia'
      fullPath: '/ia'
      preLoaderRoute: typeof AdminIaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/integrations': {
      id: '/_admin/integrations'
      path: '/integrations'
      fullPath: '/integrations'
      preLoaderRoute: typeof AdminIntegrationsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/parametres': {
      id: '/_admin/parametres'
      path: '/parametres'
      fullPath: '/parametres'
      preLoaderRoute: typeof AdminParametresRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/payment': {
      id: '/_admin/payment'
      path: '/payment'
      fullPath: '/payment'
      preLoaderRoute: typeof AdminPaymentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/produits': {
      id: '/_admin/produits'
      path: '/produits'
      fullPath: '/produits'
      preLoaderRoute: typeof AdminProduitsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/produits-gagnants': {
      id: '/_admin/produits-gagnants'
      path: '/produits-gagnants'
      fullPath: '/produits-gagnants'
      preLoaderRoute: typeof AdminProduitsGagnantsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/_admin/regles-prix': {
      id: '/_admin/regles-prix'
      path: '/regles-prix'
      fullPath: '/regles-prix'
      preLoaderRoute: typeof AdminReglesPrixRouteImport
      parentRoute: typeof AdminRoute
    }
    '/boutique/$id': {
      id: '/boutique/$id'
      path: '/$id'
      fullPath: '/boutique/$id'
      preLoaderRoute: typeof BoutiqueIdRouteImport
      parentRoute: typeof BoutiqueRoute
    }
    '/paiement/$orderId': {
      id: '/paiement/$orderId'
      path: '/paiement/$orderId'
      fullPath: '/paiement/$orderId'
      preLoaderRoute: typeof PaiementOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AdminRouteChildren {
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAssistanceRoute: typeof AdminAssistanceRoute
  AdminCatalogueRoute: typeof AdminCatalogueRoute
  AdminClientsRoute: typeof AdminClientsRoute
  AdminCommandesRoute: typeof AdminCommandesRoute
  AdminFournisseursRoute: typeof AdminFournisseursRoute
  AdminIaRoute: typeof AdminIaRoute
  AdminIntegrationsRoute: typeof AdminIntegrationsRoute
  AdminParametresRoute: typeof AdminParametresRoute
  AdminPaymentRoute: typeof AdminPaymentRoute
  AdminProduitsRoute: typeof AdminProduitsRoute
  AdminProduitsGagnantsRoute: typeof AdminProduitsGagnantsRoute
  AdminReglesPrixRoute: typeof AdminReglesPrixRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAssistanceRoute: AdminAssistanceRoute,
  AdminCatalogueRoute: AdminCatalogueRoute,
  AdminClientsRoute: AdminClientsRoute,
  AdminCommandesRoute: AdminCommandesRoute,
  AdminFournisseursRoute: AdminFournisseursRoute,
  AdminIaRoute: AdminIaRoute,
  AdminIntegrationsRoute: AdminIntegrationsRoute,
  AdminParametresRoute: AdminParametresRoute,
  AdminPaymentRoute: AdminPaymentRoute,
  AdminProduitsRoute: AdminProduitsRoute,
  AdminProduitsGagnantsRoute: AdminProduitsGagnantsRoute,
  AdminReglesPrixRoute: AdminReglesPrixRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface BoutiqueRouteChildren {
  BoutiqueIdRoute: typeof BoutiqueIdRoute
}

const BoutiqueRouteChildren: BoutiqueRouteChildren = {
  BoutiqueIdRoute: BoutiqueIdRoute,
}

const BoutiqueRouteWithChildren = BoutiqueRoute._addFileChildren(
  BoutiqueRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AdminRoute: AdminRouteWithChildren,
  BoutiqueRoute: BoutiqueRouteWithChildren,
  PanierRoute: PanierRoute,
  PaiementOrderIdRoute: PaiementOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
